purge

% Set current directory to the directory containing this file
[filepath, filename, ext] = fileparts(mfilename('fullpath'));
cd(filepath);

addpath(pwd);
addpath(fullfile(pwd,'classes'));


h = figure();

uibt = UIButtonToggle( ...
    'Play', ...
    'Pause', ...
    false, ...
    uint8(0), ...
    uint8(0), ...
    true ...
);


uibt.build(h, 10, 10, 100, 30);
