[cPath, cName, cExt] = fileparts(mfilename('fullpath'));

% Add mic
addpath(genpath(fullfile(cPath, '..', '..')));
purge;

h = figure();

uibt = UIButtonToggle( ...
    'Play', ...
    'Pause', ...
    false, ...
    uint8(0), ...
    uint8(0), ...
    true ...
);


uibt.build(h, 10, 10, 100, 30);

cb = @(src, evt) (disp('on change'));
addlistener(uibt, 'eChange', cb);